export interface RecipeData {
  title: string;
  description: string;
  cuisine: string;
  diet: string[];
  cookTimeMinutes: number;
  ingredients: string[];
}

export const recipes: RecipeData[] = [
  // === ITALIAN ===
  { title: "Classic Margherita Pizza", description: "A simple Neapolitan pizza with fresh mozzarella, San Marzano tomatoes, and basil on a thin crispy crust.", cuisine: "Italian", diet: ["Vegetarian"], cookTimeMinutes: 25, ingredients: ["pizza dough", "San Marzano tomatoes", "fresh mozzarella", "basil", "olive oil", "salt"] },
  { title: "Risotto ai Funghi", description: "Creamy Italian rice slowly cooked with porcini mushrooms, white wine, and Parmesan cheese.", cuisine: "Italian", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 40, ingredients: ["arborio rice", "porcini mushrooms", "white wine", "Parmesan", "butter", "shallots", "vegetable broth"] },
  { title: "Caprese Salad", description: "Fresh buffalo mozzarella with ripe tomatoes, basil, and a drizzle of balsamic glaze.", cuisine: "Italian", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 10, ingredients: ["buffalo mozzarella", "tomatoes", "basil", "balsamic glaze", "olive oil", "salt", "pepper"] },
  { title: "Tiramisu", description: "Layers of espresso-soaked ladyfingers and mascarpone cream dusted with cocoa powder.", cuisine: "Italian", diet: ["Vegetarian"], cookTimeMinutes: 30, ingredients: ["ladyfingers", "mascarpone", "espresso", "eggs", "sugar", "cocoa powder", "Marsala wine"] },
  { title: "Spaghetti Carbonara", description: "Classic Roman pasta with eggs, pecorino cheese, guanciale, and black pepper — no cream allowed.", cuisine: "Italian", diet: [], cookTimeMinutes: 20, ingredients: ["spaghetti", "eggs", "pecorino romano", "guanciale", "black pepper"] },
  { title: "Osso Buco", description: "Braised veal shanks in white wine and broth, served with gremolata and saffron risotto.", cuisine: "Italian", diet: ["Gluten-Free"], cookTimeMinutes: 150, ingredients: ["veal shanks", "white wine", "carrots", "celery", "onion", "tomatoes", "lemon zest", "parsley"] },
  { title: "Bruschetta al Pomodoro", description: "Toasted bread rubbed with garlic and topped with diced tomatoes, basil, and olive oil.", cuisine: "Italian", diet: ["Vegan", "Dairy-Free"], cookTimeMinutes: 10, ingredients: ["ciabatta", "tomatoes", "garlic", "basil", "olive oil", "balsamic vinegar"] },
  { title: "Panna Cotta", description: "Silky vanilla cream dessert set with gelatin, served with berry compote.", cuisine: "Italian", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 15, ingredients: ["cream", "sugar", "vanilla", "gelatin", "mixed berries", "lemon juice"] },
  { title: "Minestrone Soup", description: "Hearty Italian vegetable soup with beans, pasta, and seasonal vegetables in tomato broth.", cuisine: "Italian", diet: ["Vegan", "Dairy-Free"], cookTimeMinutes: 45, ingredients: ["cannellini beans", "pasta", "zucchini", "carrots", "celery", "tomatoes", "kale", "garlic"] },
  { title: "Eggplant Parmigiana", description: "Layers of fried eggplant with marinara sauce, mozzarella, and Parmesan baked until bubbly.", cuisine: "Italian", diet: ["Vegetarian"], cookTimeMinutes: 60, ingredients: ["eggplant", "marinara sauce", "mozzarella", "Parmesan", "breadcrumbs", "eggs", "basil"] },

  // === INDIAN ===
  { title: "Chicken Tikka Masala", description: "Tender chicken pieces in a creamy spiced tomato sauce, a beloved British-Indian classic.", cuisine: "Indian", diet: ["Gluten-Free"], cookTimeMinutes: 45, ingredients: ["chicken thighs", "yogurt", "garam masala", "tomato puree", "cream", "ginger", "garlic", "cumin"] },
  { title: "Butter Chicken", description: "Tender tandoori chicken in a velvety tomato-butter sauce with aromatic spices and cream.", cuisine: "Indian", diet: ["Gluten-Free"], cookTimeMinutes: 50, ingredients: ["chicken", "butter", "tomato puree", "cream", "garam masala", "fenugreek leaves", "ginger", "garlic"] },
  { title: "Palak Paneer", description: "Cubes of fresh paneer cheese in a vibrant spinach sauce spiced with cumin and garam masala.", cuisine: "Indian", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 35, ingredients: ["paneer", "spinach", "onion", "tomatoes", "cumin", "garam masala", "cream", "garlic"] },
  { title: "Chana Masala", description: "Spiced chickpea curry in a tangy tomato-onion sauce — a North Indian staple.", cuisine: "Indian", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 30, ingredients: ["chickpeas", "tomatoes", "onion", "ginger", "garlic", "cumin", "coriander", "amchur"] },
  { title: "Biryani", description: "Fragrant basmati rice layered with spiced meat, caramelized onions, and saffron.", cuisine: "Indian", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 90, ingredients: ["basmati rice", "lamb", "onions", "yogurt", "saffron", "cardamom", "cinnamon", "bay leaves"] },
  { title: "Samosas", description: "Crispy fried pastry triangles stuffed with spiced potatoes and peas.", cuisine: "Indian", diet: ["Vegan", "Dairy-Free"], cookTimeMinutes: 45, ingredients: ["potatoes", "peas", "flour", "cumin", "coriander", "green chili", "ginger", "oil"] },
  { title: "Dal Tadka", description: "Comforting yellow lentils tempered with cumin, garlic, and dried red chilies.", cuisine: "Indian", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 30, ingredients: ["yellow lentils", "cumin", "garlic", "dried red chilies", "turmeric", "tomatoes", "cilantro"] },
  { title: "Tandoori Chicken", description: "Yogurt-marinated chicken roasted in a clay oven until charred and smoky.", cuisine: "Indian", diet: ["Gluten-Free"], cookTimeMinutes: 40, ingredients: ["chicken", "yogurt", "tandoori masala", "lemon juice", "ginger", "garlic", "kashmiri chili"] },

  // === THAI ===
  { title: "Pad Thai", description: "Stir-fried rice noodles with shrimp, tofu, peanuts, and tamarind sauce — Thailand's most famous street food.", cuisine: "Thai", diet: [], cookTimeMinutes: 30, ingredients: ["rice noodles", "shrimp", "tofu", "bean sprouts", "peanuts", "tamarind paste", "fish sauce", "lime"] },
  { title: "Tom Yum Soup", description: "A hot and sour Thai soup with shrimp, mushrooms, lemongrass, and kaffir lime leaves.", cuisine: "Thai", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 20, ingredients: ["shrimp", "lemongrass", "galangal", "kaffir lime leaves", "mushrooms", "chili", "fish sauce", "lime juice"] },
  { title: "Green Curry", description: "Thai green curry with coconut milk, bamboo shoots, Thai basil, and your choice of protein.", cuisine: "Thai", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 30, ingredients: ["green curry paste", "coconut milk", "chicken", "bamboo shoots", "Thai basil", "fish sauce", "palm sugar", "eggplant"] },
  { title: "Massaman Curry", description: "Rich and mild Thai curry with potatoes, peanuts, and warm spices influenced by Indian cuisine.", cuisine: "Thai", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 50, ingredients: ["massaman curry paste", "coconut milk", "beef", "potatoes", "peanuts", "tamarind", "palm sugar", "cinnamon"] },
  { title: "Som Tum (Green Papaya Salad)", description: "Spicy and tangy shredded green papaya salad with tomatoes, peanuts, and dried shrimp.", cuisine: "Thai", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 15, ingredients: ["green papaya", "tomatoes", "peanuts", "dried shrimp", "lime juice", "fish sauce", "chili", "garlic"] },
  { title: "Mango Sticky Rice", description: "Sweet coconut sticky rice served with fresh ripe mango slices — Thailand's beloved dessert.", cuisine: "Thai", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 40, ingredients: ["sticky rice", "coconut milk", "sugar", "salt", "ripe mango"] },
  { title: "Pad Kra Pao", description: "Stir-fried holy basil with minced pork, chili, garlic, and a fried egg on rice.", cuisine: "Thai", diet: ["Dairy-Free"], cookTimeMinutes: 15, ingredients: ["minced pork", "holy basil", "garlic", "chili", "soy sauce", "oyster sauce", "egg", "rice"] },

  // === JAPANESE ===
  { title: "Sushi Rolls (Maki)", description: "Hand-rolled sushi with seasoned rice, fresh fish, and vegetables wrapped in nori seaweed.", cuisine: "Japanese", diet: ["Dairy-Free"], cookTimeMinutes: 60, ingredients: ["sushi rice", "nori", "salmon", "avocado", "cucumber", "rice vinegar", "wasabi", "soy sauce"] },
  { title: "Ramen (Tonkotsu)", description: "Rich pork bone broth ramen with chashu pork, soft-boiled egg, nori, and green onions.", cuisine: "Japanese", diet: ["Dairy-Free"], cookTimeMinutes: 240, ingredients: ["pork bones", "ramen noodles", "chashu pork", "soft-boiled egg", "nori", "green onions", "soy sauce", "mirin"] },
  { title: "Tempura", description: "Light and crispy battered shrimp and vegetables served with tentsuyu dipping sauce.", cuisine: "Japanese", diet: ["Dairy-Free"], cookTimeMinutes: 25, ingredients: ["shrimp", "sweet potato", "green beans", "flour", "egg", "ice water", "dashi", "soy sauce"] },
  { title: "Teriyaki Salmon", description: "Glazed salmon fillets with a sweet and savory teriyaki sauce, served over steamed rice.", cuisine: "Japanese", diet: ["Dairy-Free", "Gluten-Free"], cookTimeMinutes: 20, ingredients: ["salmon", "soy sauce", "mirin", "sake", "sugar", "ginger", "rice", "sesame seeds"] },
  { title: "Miso Soup", description: "Simple and comforting Japanese soup with tofu, wakame seaweed, and green onions in dashi broth.", cuisine: "Japanese", diet: ["Vegan", "Dairy-Free"], cookTimeMinutes: 10, ingredients: ["miso paste", "tofu", "wakame", "dashi", "green onions"] },
  { title: "Okonomiyaki", description: "Savory Japanese cabbage pancake topped with mayo, okonomiyaki sauce, and bonito flakes.", cuisine: "Japanese", diet: [], cookTimeMinutes: 25, ingredients: ["cabbage", "flour", "eggs", "dashi", "pork belly", "okonomiyaki sauce", "mayo", "bonito flakes"] },
  { title: "Gyoza", description: "Pan-fried Japanese dumplings with a juicy pork and cabbage filling and crispy bottom.", cuisine: "Japanese", diet: ["Dairy-Free"], cookTimeMinutes: 30, ingredients: ["ground pork", "cabbage", "garlic", "ginger", "soy sauce", "sesame oil", "gyoza wrappers"] },

  // === MEXICAN ===
  { title: "Tacos al Pastor", description: "Marinated pork tacos with pineapple, cilantro, and onion on soft corn tortillas — Mexico City street food.", cuisine: "Mexican", diet: ["Dairy-Free"], cookTimeMinutes: 40, ingredients: ["pork shoulder", "pineapple", "corn tortillas", "cilantro", "onion", "achiote paste", "lime"] },
  { title: "Guacamole", description: "Fresh avocado dip with lime, cilantro, onion, and jalapeño — the perfect party starter.", cuisine: "Mexican", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 10, ingredients: ["avocados", "lime juice", "cilantro", "red onion", "jalapeño", "tomato", "salt"] },
  { title: "Enchiladas Verdes", description: "Corn tortillas filled with chicken, rolled and smothered in tangy tomatillo salsa verde.", cuisine: "Mexican", diet: ["Gluten-Free"], cookTimeMinutes: 40, ingredients: ["corn tortillas", "chicken", "tomatillos", "jalapeño", "sour cream", "cheese", "onion", "cilantro"] },
  { title: "Elote (Mexican Street Corn)", description: "Grilled corn on the cob slathered with mayo, cotija cheese, chili powder, and lime.", cuisine: "Mexican", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 15, ingredients: ["corn", "mayo", "cotija cheese", "chili powder", "lime", "cilantro", "butter"] },
  { title: "Pozole Rojo", description: "Hearty Mexican hominy soup with pork in a rich red chili broth, topped with cabbage and radish.", cuisine: "Mexican", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 120, ingredients: ["hominy", "pork shoulder", "dried guajillo chilis", "garlic", "onion", "oregano", "cabbage", "radish"] },
  { title: "Churros", description: "Crispy fried dough sticks coated in cinnamon sugar, served with thick chocolate dipping sauce.", cuisine: "Mexican", diet: ["Vegetarian"], cookTimeMinutes: 30, ingredients: ["flour", "butter", "eggs", "sugar", "cinnamon", "oil", "chocolate", "milk"] },
  { title: "Black Bean Tacos", description: "Smoky spiced black beans in warm tortillas with pickled onion, avocado, and cotija cheese.", cuisine: "Mexican", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 20, ingredients: ["black beans", "corn tortillas", "avocado", "pickled red onion", "cotija cheese", "cumin", "smoked paprika", "lime"] },

  // === FRENCH ===
  { title: "Beef Bourguignon", description: "A rich French stew of beef braised in red wine with mushrooms, pearl onions, and bacon.", cuisine: "French", diet: [], cookTimeMinutes: 180, ingredients: ["beef chuck", "red wine", "mushrooms", "pearl onions", "bacon", "carrots", "thyme", "bay leaf"] },
  { title: "Chocolate Lava Cake", description: "Individual warm chocolate cakes with a molten center, served with vanilla ice cream.", cuisine: "French", diet: ["Vegetarian"], cookTimeMinutes: 20, ingredients: ["dark chocolate", "butter", "eggs", "sugar", "flour", "vanilla extract"] },
  { title: "Coq au Vin", description: "Chicken braised in red wine with mushrooms, lardons, and pearl onions — rustic French comfort food.", cuisine: "French", diet: ["Gluten-Free"], cookTimeMinutes: 120, ingredients: ["chicken", "red wine", "mushrooms", "lardons", "pearl onions", "garlic", "thyme", "bay leaf"] },
  { title: "French Onion Soup", description: "Caramelized onion soup topped with crusty bread and melted Gruyère cheese.", cuisine: "French", diet: ["Vegetarian"], cookTimeMinutes: 60, ingredients: ["onions", "butter", "beef broth", "white wine", "baguette", "Gruyère cheese", "thyme"] },
  { title: "Crêpes Suzette", description: "Thin French pancakes flambéed in orange butter sauce with Grand Marnier.", cuisine: "French", diet: ["Vegetarian"], cookTimeMinutes: 30, ingredients: ["flour", "eggs", "milk", "butter", "orange juice", "orange zest", "sugar", "Grand Marnier"] },
  { title: "Ratatouille", description: "Provençal vegetable stew with eggplant, zucchini, peppers, and tomatoes in herbed olive oil.", cuisine: "French", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 50, ingredients: ["eggplant", "zucchini", "bell peppers", "tomatoes", "onion", "garlic", "herbes de Provence", "olive oil"] },
  { title: "Quiche Lorraine", description: "Savory custard tart with bacon, Gruyère cheese, and caramelized onions in a flaky crust.", cuisine: "French", diet: [], cookTimeMinutes: 50, ingredients: ["pie crust", "bacon", "Gruyère", "eggs", "cream", "onion", "nutmeg"] },

  // === KOREAN ===
  { title: "Bibimbap", description: "Korean mixed rice bowl topped with sautéed vegetables, gochujang, a fried egg, and sesame oil.", cuisine: "Korean", diet: ["Vegetarian"], cookTimeMinutes: 40, ingredients: ["rice", "spinach", "carrots", "zucchini", "mushrooms", "gochujang", "sesame oil", "egg"] },
  { title: "Kimchi Fried Rice", description: "Spicy stir-fried rice with aged kimchi, pork belly, and a crispy fried egg on top.", cuisine: "Korean", diet: ["Dairy-Free"], cookTimeMinutes: 15, ingredients: ["rice", "kimchi", "pork belly", "egg", "sesame oil", "gochujang", "green onions", "sesame seeds"] },
  { title: "Korean Fried Chicken", description: "Double-fried chicken wings tossed in a sweet and spicy gochujang glaze.", cuisine: "Korean", diet: ["Dairy-Free"], cookTimeMinutes: 45, ingredients: ["chicken wings", "gochujang", "soy sauce", "honey", "garlic", "ginger", "cornstarch", "sesame seeds"] },
  { title: "Japchae", description: "Stir-fried glass noodles with vegetables, beef, and sesame-soy sauce — a Korean celebration dish.", cuisine: "Korean", diet: ["Dairy-Free"], cookTimeMinutes: 30, ingredients: ["sweet potato noodles", "beef", "spinach", "carrots", "mushrooms", "soy sauce", "sesame oil", "garlic"] },
  { title: "Tteokbokki", description: "Chewy rice cakes in a fiery gochujang sauce with fish cakes and green onions.", cuisine: "Korean", diet: ["Dairy-Free"], cookTimeMinutes: 20, ingredients: ["rice cakes", "gochujang", "fish cakes", "green onions", "sugar", "soy sauce", "garlic", "dashi"] },
  { title: "Bulgogi", description: "Thinly sliced beef marinated in soy, sesame, and pear, grilled over high heat.", cuisine: "Korean", diet: ["Dairy-Free", "Gluten-Free"], cookTimeMinutes: 25, ingredients: ["beef sirloin", "soy sauce", "sesame oil", "pear", "garlic", "ginger", "green onions", "sugar"] },

  // === MIDDLE EASTERN ===
  { title: "Falafel Bowl", description: "Crispy chickpea fritters served over hummus with tabbouleh, pickled vegetables, and tahini drizzle.", cuisine: "Middle Eastern", diet: ["Vegan", "Dairy-Free"], cookTimeMinutes: 35, ingredients: ["chickpeas", "parsley", "cumin", "tahini", "lemon", "bulgur wheat", "tomatoes", "cucumber"] },
  { title: "Shakshuka", description: "Eggs poached in a spiced tomato and pepper sauce, served with crusty bread for dipping.", cuisine: "Middle Eastern", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 25, ingredients: ["eggs", "tomatoes", "bell peppers", "onion", "cumin", "paprika", "garlic", "feta cheese"] },
  { title: "Hummus", description: "Creamy blended chickpea dip with tahini, lemon, and garlic — the ultimate mezze staple.", cuisine: "Middle Eastern", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 10, ingredients: ["chickpeas", "tahini", "lemon juice", "garlic", "olive oil", "cumin", "salt"] },
  { title: "Shawarma", description: "Spiced meat carved from a rotating spit, served in pita with garlic sauce and pickled turnips.", cuisine: "Middle Eastern", diet: ["Dairy-Free"], cookTimeMinutes: 30, ingredients: ["chicken thighs", "cumin", "turmeric", "paprika", "garlic", "pita bread", "pickled turnips", "garlic sauce"] },
  { title: "Baba Ganoush", description: "Smoky roasted eggplant dip blended with tahini, lemon, and garlic.", cuisine: "Middle Eastern", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 40, ingredients: ["eggplant", "tahini", "lemon juice", "garlic", "olive oil", "parsley", "pomegranate seeds"] },
  { title: "Lamb Kofta", description: "Grilled spiced lamb skewers with mint yogurt sauce and warm flatbread.", cuisine: "Middle Eastern", diet: [], cookTimeMinutes: 25, ingredients: ["ground lamb", "onion", "parsley", "cumin", "coriander", "yogurt", "mint", "flatbread"] },

  // === AMERICAN ===
  { title: "Caesar Salad", description: "Crisp romaine lettuce with creamy Caesar dressing, croutons, and shaved Parmesan.", cuisine: "American", diet: ["Vegetarian"], cookTimeMinutes: 15, ingredients: ["romaine lettuce", "Parmesan", "croutons", "anchovy paste", "garlic", "lemon juice", "egg yolk", "olive oil"] },
  { title: "Avocado Toast", description: "Smashed avocado on sourdough with chili flakes, microgreens, and a poached egg.", cuisine: "American", diet: ["Vegetarian"], cookTimeMinutes: 10, ingredients: ["avocado", "sourdough bread", "egg", "chili flakes", "lemon juice", "microgreens", "salt", "olive oil"] },
  { title: "Eggs Benedict", description: "Poached eggs on English muffins with Canadian bacon and silky hollandaise sauce.", cuisine: "American", diet: [], cookTimeMinutes: 25, ingredients: ["eggs", "English muffins", "Canadian bacon", "butter", "lemon juice", "egg yolks", "cayenne pepper"] },
  { title: "BBQ Pulled Pork", description: "Slow-smoked pork shoulder shredded and tossed in tangy barbecue sauce, served on brioche buns.", cuisine: "American", diet: ["Dairy-Free"], cookTimeMinutes: 480, ingredients: ["pork shoulder", "BBQ sauce", "apple cider vinegar", "brown sugar", "paprika", "garlic powder", "brioche buns", "coleslaw"] },
  { title: "Clam Chowder", description: "Creamy New England soup with tender clams, potatoes, and bacon in a rich broth.", cuisine: "American", diet: [], cookTimeMinutes: 40, ingredients: ["clams", "potatoes", "bacon", "onion", "celery", "cream", "butter", "thyme"] },
  { title: "Buffalo Wings", description: "Crispy fried chicken wings tossed in spicy cayenne butter sauce with blue cheese dip.", cuisine: "American", diet: ["Gluten-Free"], cookTimeMinutes: 35, ingredients: ["chicken wings", "cayenne hot sauce", "butter", "garlic powder", "blue cheese", "celery", "carrots"] },
  { title: "Pancakes with Maple Syrup", description: "Fluffy buttermilk pancakes stacked high with butter and pure maple syrup.", cuisine: "American", diet: ["Vegetarian"], cookTimeMinutes: 20, ingredients: ["flour", "buttermilk", "eggs", "butter", "baking powder", "sugar", "maple syrup"] },

  // === CHINESE ===
  { title: "Dumplings (Jiaozi)", description: "Pan-fried pork and cabbage dumplings with a crispy bottom and savory dipping sauce.", cuisine: "Chinese", diet: ["Dairy-Free"], cookTimeMinutes: 45, ingredients: ["ground pork", "cabbage", "ginger", "garlic", "soy sauce", "sesame oil", "dumpling wrappers", "rice vinegar"] },
  { title: "Kung Pao Chicken", description: "Stir-fried chicken with peanuts, dried chilies, and Sichuan peppercorns in a savory-sweet sauce.", cuisine: "Chinese", diet: ["Dairy-Free"], cookTimeMinutes: 25, ingredients: ["chicken breast", "peanuts", "dried chilies", "Sichuan peppercorns", "soy sauce", "rice vinegar", "sugar", "garlic"] },
  { title: "Mapo Tofu", description: "Silken tofu in a fiery Sichuan sauce with ground pork, doubanjiang, and numbing peppercorns.", cuisine: "Chinese", diet: ["Dairy-Free"], cookTimeMinutes: 20, ingredients: ["silken tofu", "ground pork", "doubanjiang", "Sichuan peppercorns", "garlic", "ginger", "green onions", "soy sauce"] },
  { title: "Char Siu (BBQ Pork)", description: "Cantonese-style roasted pork with a sweet and sticky honey-hoisin glaze.", cuisine: "Chinese", diet: ["Dairy-Free"], cookTimeMinutes: 60, ingredients: ["pork shoulder", "hoisin sauce", "honey", "soy sauce", "five-spice powder", "garlic", "red food coloring"] },
  { title: "Hot and Sour Soup", description: "Tangy and spicy soup with tofu, mushrooms, bamboo shoots, and egg ribbons.", cuisine: "Chinese", diet: ["Dairy-Free"], cookTimeMinutes: 20, ingredients: ["tofu", "mushrooms", "bamboo shoots", "eggs", "rice vinegar", "white pepper", "soy sauce", "cornstarch"] },
  { title: "Scallion Pancakes", description: "Flaky, crispy pan-fried flatbread layered with chopped scallions and sesame oil.", cuisine: "Chinese", diet: ["Vegan", "Dairy-Free"], cookTimeMinutes: 30, ingredients: ["flour", "boiling water", "scallions", "sesame oil", "salt", "oil"] },
  { title: "Dan Dan Noodles", description: "Spicy Sichuan noodles with minced pork, chili oil, and preserved vegetables.", cuisine: "Chinese", diet: ["Dairy-Free"], cookTimeMinutes: 20, ingredients: ["wheat noodles", "ground pork", "chili oil", "soy sauce", "sesame paste", "Sichuan peppercorns", "preserved vegetables", "peanuts"] },

  // === SPANISH ===
  { title: "Paella Valenciana", description: "Saffron-infused Spanish rice with chicken, rabbit, green beans, and snails — the original Valencia recipe.", cuisine: "Spanish", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 60, ingredients: ["bomba rice", "saffron", "chicken", "rabbit", "green beans", "tomatoes", "olive oil", "rosemary"] },
  { title: "Gazpacho", description: "Chilled Spanish tomato soup blended with peppers, cucumber, and sherry vinegar — perfect for summer.", cuisine: "Spanish", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 15, ingredients: ["tomatoes", "cucumber", "red pepper", "garlic", "olive oil", "sherry vinegar", "bread", "onion"] },
  { title: "Patatas Bravas", description: "Crispy fried potato cubes with spicy bravas sauce and garlic aioli.", cuisine: "Spanish", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 30, ingredients: ["potatoes", "olive oil", "tomato sauce", "smoked paprika", "cayenne", "garlic", "mayo", "lemon"] },
  { title: "Gambas al Ajillo", description: "Sizzling garlic shrimp cooked in olive oil with chili flakes and parsley.", cuisine: "Spanish", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 10, ingredients: ["shrimp", "garlic", "olive oil", "chili flakes", "parsley", "white wine", "bread"] },
  { title: "Tortilla Española", description: "Classic Spanish potato and onion omelette, served warm or at room temperature.", cuisine: "Spanish", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 35, ingredients: ["potatoes", "eggs", "onion", "olive oil", "salt"] },
  { title: "Churros con Chocolate", description: "Crispy fried dough sticks served with thick, rich Spanish hot chocolate for dipping.", cuisine: "Spanish", diet: ["Vegetarian"], cookTimeMinutes: 25, ingredients: ["flour", "water", "butter", "salt", "sugar", "cinnamon", "dark chocolate", "milk"] },

  // === VIETNAMESE ===
  { title: "Pho Bo", description: "Vietnamese beef noodle soup with a fragrant star anise and cinnamon broth, served with fresh herbs.", cuisine: "Vietnamese", diet: ["Dairy-Free"], cookTimeMinutes: 120, ingredients: ["beef bones", "rice noodles", "star anise", "cinnamon", "ginger", "bean sprouts", "basil", "hoisin sauce"] },
  { title: "Banh Mi", description: "Crusty baguette filled with pâté, pickled vegetables, cilantro, jalapeño, and grilled pork.", cuisine: "Vietnamese", diet: ["Dairy-Free"], cookTimeMinutes: 25, ingredients: ["baguette", "pork", "pâté", "pickled carrots", "daikon", "cilantro", "jalapeño", "mayo"] },
  { title: "Goi Cuon (Spring Rolls)", description: "Fresh rice paper rolls filled with shrimp, vermicelli, herbs, and served with peanut sauce.", cuisine: "Vietnamese", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 20, ingredients: ["rice paper", "shrimp", "vermicelli", "lettuce", "mint", "cilantro", "peanut butter", "hoisin sauce"] },
  { title: "Bun Cha", description: "Grilled pork patties and belly served with rice noodles, herbs, and sweet fish sauce dip.", cuisine: "Vietnamese", diet: ["Dairy-Free", "Gluten-Free"], cookTimeMinutes: 35, ingredients: ["ground pork", "pork belly", "rice noodles", "fish sauce", "sugar", "garlic", "lettuce", "herbs"] },
  { title: "Ca Kho To (Caramelized Fish)", description: "Catfish braised in a clay pot with caramel sauce, fish sauce, and black pepper.", cuisine: "Vietnamese", diet: ["Dairy-Free", "Gluten-Free"], cookTimeMinutes: 30, ingredients: ["catfish", "sugar", "fish sauce", "black pepper", "shallots", "garlic", "coconut water"] },

  // === GREEK ===
  { title: "Greek Moussaka", description: "Layered eggplant and spiced lamb casserole topped with creamy béchamel sauce.", cuisine: "Greek", diet: [], cookTimeMinutes: 90, ingredients: ["eggplant", "ground lamb", "tomatoes", "onion", "cinnamon", "béchamel sauce", "Parmesan", "nutmeg"] },
  { title: "Souvlaki", description: "Grilled marinated pork skewers served in pita with tzatziki, tomatoes, and onions.", cuisine: "Greek", diet: [], cookTimeMinutes: 25, ingredients: ["pork", "olive oil", "lemon", "oregano", "pita bread", "tzatziki", "tomatoes", "red onion"] },
  { title: "Spanakopita", description: "Flaky phyllo pastry filled with spinach, feta cheese, and fresh herbs.", cuisine: "Greek", diet: ["Vegetarian"], cookTimeMinutes: 45, ingredients: ["phyllo dough", "spinach", "feta cheese", "onion", "dill", "eggs", "olive oil", "butter"] },
  { title: "Greek Salad", description: "Chunky tomatoes, cucumber, red onion, olives, and feta with oregano and olive oil.", cuisine: "Greek", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 10, ingredients: ["tomatoes", "cucumber", "red onion", "kalamata olives", "feta cheese", "oregano", "olive oil"] },
  { title: "Tzatziki", description: "Cool and creamy yogurt dip with cucumber, garlic, dill, and lemon.", cuisine: "Greek", diet: ["Vegetarian", "Gluten-Free"], cookTimeMinutes: 10, ingredients: ["Greek yogurt", "cucumber", "garlic", "dill", "lemon juice", "olive oil", "salt"] },

  // === MOROCCAN ===
  { title: "Lamb Tagine", description: "Slow-cooked Moroccan lamb with apricots, almonds, and warm spices in a conical clay pot.", cuisine: "Moroccan", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 150, ingredients: ["lamb shoulder", "dried apricots", "almonds", "cinnamon", "cumin", "honey", "onions", "saffron"] },
  { title: "Couscous Royale", description: "Fluffy semolina couscous with seven vegetables, lamb, and merguez sausage.", cuisine: "Moroccan", diet: ["Dairy-Free"], cookTimeMinutes: 90, ingredients: ["couscous", "lamb", "merguez", "zucchini", "carrots", "turnips", "chickpeas", "harissa"] },
  { title: "Harira", description: "Hearty Moroccan soup with lentils, chickpeas, tomatoes, and warming spices — traditional Ramadan fare.", cuisine: "Moroccan", diet: ["Vegan", "Dairy-Free"], cookTimeMinutes: 45, ingredients: ["lentils", "chickpeas", "tomatoes", "onion", "celery", "ginger", "cinnamon", "cilantro"] },

  // === PERUVIAN ===
  { title: "Ceviche", description: "Fresh raw fish cured in citrus juices with red onion, cilantro, and chili peppers.", cuisine: "Peruvian", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 20, ingredients: ["white fish", "lime juice", "red onion", "cilantro", "chili pepper", "sweet potato", "corn"] },
  { title: "Lomo Saltado", description: "Peruvian stir-fry of beef, tomatoes, and onions with soy sauce, served over fries and rice.", cuisine: "Peruvian", diet: ["Dairy-Free"], cookTimeMinutes: 25, ingredients: ["beef sirloin", "tomatoes", "red onion", "soy sauce", "vinegar", "french fries", "rice", "cilantro"] },
  { title: "Aji de Gallina", description: "Shredded chicken in a creamy walnut and yellow pepper sauce over rice.", cuisine: "Peruvian", diet: ["Gluten-Free"], cookTimeMinutes: 45, ingredients: ["chicken", "aji amarillo", "walnuts", "bread", "Parmesan", "evaporated milk", "onion", "garlic"] },

  // === BRITISH ===
  { title: "Fish and Chips", description: "Beer-battered cod with thick-cut chips, mushy peas, and tartar sauce — the British pub classic.", cuisine: "British", diet: [], cookTimeMinutes: 35, ingredients: ["cod fillets", "flour", "beer", "potatoes", "peas", "tartar sauce", "lemon", "malt vinegar"] },
  { title: "Banoffee Pie", description: "A no-bake British dessert with layers of toffee, bananas, and whipped cream on a biscuit base.", cuisine: "British", diet: ["Vegetarian"], cookTimeMinutes: 30, ingredients: ["digestive biscuits", "butter", "condensed milk", "bananas", "whipping cream", "dark chocolate"] },
  { title: "Shepherd's Pie", description: "Savory lamb mince with vegetables topped with creamy mashed potatoes and baked golden.", cuisine: "British", diet: ["Gluten-Free"], cookTimeMinutes: 60, ingredients: ["lamb mince", "potatoes", "carrots", "peas", "onion", "tomato paste", "Worcestershire sauce", "butter"] },
  { title: "Full English Breakfast", description: "The classic fry-up with bacon, eggs, sausages, beans, toast, tomatoes, and mushrooms.", cuisine: "British", diet: [], cookTimeMinutes: 20, ingredients: ["bacon", "eggs", "sausages", "baked beans", "toast", "tomatoes", "mushrooms", "butter"] },
  { title: "Sticky Toffee Pudding", description: "Moist date sponge cake drenched in warm toffee sauce, served with vanilla custard.", cuisine: "British", diet: ["Vegetarian"], cookTimeMinutes: 45, ingredients: ["dates", "flour", "butter", "brown sugar", "eggs", "cream", "vanilla", "baking soda"] },

  // === CARIBBEAN ===
  { title: "Jerk Chicken", description: "Spicy Jamaican grilled chicken marinated in scotch bonnet peppers, allspice, and thyme.", cuisine: "Caribbean", diet: ["Gluten-Free", "Dairy-Free"], cookTimeMinutes: 60, ingredients: ["chicken", "scotch bonnet peppers", "allspice", "thyme", "garlic", "ginger", "soy sauce", "lime"] },
  { title: "Rice and Peas", description: "Coconut-infused rice cooked with kidney beans, thyme, and scotch bonnet — a Jamaican staple.", cuisine: "Caribbean", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 35, ingredients: ["rice", "kidney beans", "coconut milk", "thyme", "scotch bonnet", "garlic", "scallions"] },
  { title: "Plantain Fritters", description: "Sweet ripe plantains fried until golden and caramelized — a simple Caribbean treat.", cuisine: "Caribbean", diet: ["Vegan", "Gluten-Free", "Dairy-Free"], cookTimeMinutes: 15, ingredients: ["ripe plantains", "oil", "salt", "cinnamon"] },

  // === ETHIOPIAN ===
  { title: "Doro Wat", description: "Spicy Ethiopian chicken stew with berbere spice, hard-boiled eggs, and injera bread.", cuisine: "Ethiopian", diet: ["Dairy-Free"], cookTimeMinutes: 90, ingredients: ["chicken", "berbere spice", "onions", "garlic", "ginger", "eggs", "niter kibbeh", "injera"] },
  { title: "Misir Wat", description: "Spiced red lentil stew with berbere and served on spongy injera flatbread.", cuisine: "Ethiopian", diet: ["Vegan", "Dairy-Free"], cookTimeMinutes: 40, ingredients: ["red lentils", "berbere spice", "onions", "garlic", "tomato paste", "oil", "injera"] },

  // === TURKISH ===
  { title: "Lahmacun", description: "Thin crispy Turkish flatbread topped with spiced minced meat, herbs, and lemon.", cuisine: "Turkish", diet: ["Dairy-Free"], cookTimeMinutes: 20, ingredients: ["flatbread dough", "ground lamb", "tomatoes", "onion", "parsley", "red pepper flakes", "lemon", "sumac"] },
  { title: "Iskender Kebab", description: "Sliced döner meat over pita bread with tomato sauce, yogurt, and browned butter.", cuisine: "Turkish", diet: [], cookTimeMinutes: 30, ingredients: ["lamb döner", "pita bread", "tomato sauce", "yogurt", "butter", "green peppers"] },
  { title: "Baklava", description: "Layers of crispy phyllo pastry filled with chopped nuts and soaked in honey syrup.", cuisine: "Turkish", diet: ["Vegetarian"], cookTimeMinutes: 60, ingredients: ["phyllo dough", "pistachios", "walnuts", "butter", "sugar", "honey", "lemon juice", "cinnamon"] },
];
