export interface TravelDestination {
  id: string;
  name: string;
  description: string;
  country: string;
  region: string;
  type: string;
  bestSeason: string[];
  activities: string[];
  budget: string;
  climate: string;
}

export const destinations: TravelDestination[] = [
  // Beach & Islands
  { id: "1", name: "Bali, Indonesia", description: "Tropical paradise with lush rice terraces, ancient temples, vibrant nightlife, and world-class surfing. Perfect blend of culture, nature, and relaxation.", country: "Indonesia", region: "Southeast Asia", type: "Beach & Culture", bestSeason: ["Apr-Oct"], activities: ["Surfing", "Temples", "Rice Terraces", "Yoga"], budget: "$$", climate: "Tropical" },
  { id: "2", name: "Maldives", description: "Crystal-clear turquoise waters with overwater bungalows, pristine white sand beaches, and incredible snorkeling with manta rays and whale sharks.", country: "Maldives", region: "Indian Ocean", type: "Luxury Beach", bestSeason: ["Nov-Apr"], activities: ["Snorkeling", "Diving", "Spa", "Sunset Cruise"], budget: "$$$", climate: "Tropical" },
  { id: "3", name: "Santorini, Greece", description: "Iconic white-washed buildings with blue domes perched on volcanic cliffs, stunning sunsets over the caldera, and excellent local wine.", country: "Greece", region: "Europe", type: "Romantic Island", bestSeason: ["May-Oct"], activities: ["Wine Tasting", "Sunset Watching", "Sailing", "Photography"], budget: "$$$", climate: "Mediterranean" },
  { id: "4", name: "Phuket, Thailand", description: "Bustling Thai island with beautiful beaches, vibrant night markets, Buddhist temples, and affordable luxury resorts.", country: "Thailand", region: "Southeast Asia", type: "Beach & Nightlife", bestSeason: ["Nov-Mar"], activities: ["Beach", "Night Markets", "Island Hopping", "Thai Massage"], budget: "$", climate: "Tropical" },
  { id: "5", name: "Amalfi Coast, Italy", description: "Dramatic cliffside villages cascading down to the Mediterranean, with colorful houses, lemon groves, and incredible Italian cuisine.", country: "Italy", region: "Europe", type: "Coastal Scenic", bestSeason: ["May-Sep"], activities: ["Hiking", "Boat Tours", "Food Tours", "Swimming"], budget: "$$$", climate: "Mediterranean" },
  { id: "6", name: "Zanzibar, Tanzania", description: "Spice island off East Africa with pristine beaches, historic Stone Town, and incredible marine life. A mix of African, Arab, and Indian cultures.", country: "Tanzania", region: "East Africa", type: "Beach & Culture", bestSeason: ["Jun-Oct"], activities: ["Snorkeling", "Spice Tours", "Stone Town", "Dhow Sailing"], budget: "$$", climate: "Tropical" },

  // Adventure & Nature
  { id: "7", name: "Patagonia, Argentina/Chile", description: "Vast wilderness of glaciers, jagged peaks, and turquoise lakes at the end of the world. Epic hiking through untouched landscapes.", country: "Argentina/Chile", region: "South America", type: "Adventure & Hiking", bestSeason: ["Oct-Mar"], activities: ["Trekking", "Glacier Walking", "Wildlife", "Photography"], budget: "$$", climate: "Cold & Windy" },
  { id: "8", name: "Iceland", description: "Land of fire and ice with erupting geysers, northern lights, volcanic landscapes, hot springs, and dramatic waterfalls around every corner.", country: "Iceland", region: "Europe", type: "Nature & Adventure", bestSeason: ["Jun-Aug", "Sep-Mar for Northern Lights"], activities: ["Northern Lights", "Hot Springs", "Glacier Hiking", "Whale Watching"], budget: "$$$", climate: "Subarctic" },
  { id: "9", name: "New Zealand", description: "Adventure capital of the world with fjords, mountains, glowworm caves, and Hobbiton. Stunning landscapes from Lord of the Rings brought to life.", country: "New Zealand", region: "Oceania", type: "Adventure & Scenic", bestSeason: ["Dec-Feb"], activities: ["Bungee Jumping", "Hiking", "Kayaking", "Hobbiton"], budget: "$$", climate: "Temperate" },
  { id: "10", name: "Swiss Alps", description: "Majestic snow-capped peaks, charming mountain villages, world-class skiing, and scenic train rides through breathtaking alpine scenery.", country: "Switzerland", region: "Europe", type: "Mountain & Skiing", bestSeason: ["Dec-Mar", "Jun-Sep"], activities: ["Skiing", "Hiking", "Scenic Trains", "Fondue"], budget: "$$$", climate: "Alpine" },
  { id: "11", name: "Costa Rica", description: "Biodiversity hotspot with rainforests, volcanoes, and both Pacific and Caribbean coastlines. Zip-lining through cloud forests and spotting sloths.", country: "Costa Rica", region: "Central America", type: "Eco-Adventure", bestSeason: ["Dec-Apr"], activities: ["Zip-lining", "Wildlife", "Surfing", "Volcano Hiking"], budget: "$$", climate: "Tropical" },
  { id: "12", name: "Norwegian Fjords", description: "Dramatic narrow inlets carved by glaciers, surrounded by towering cliffs and cascading waterfalls. Kayak through mirror-still waters.", country: "Norway", region: "Europe", type: "Nature & Scenic", bestSeason: ["May-Sep"], activities: ["Fjord Cruises", "Kayaking", "Hiking", "Fishing"], budget: "$$$", climate: "Cool Maritime" },

  // Cultural & Historical
  { id: "13", name: "Kyoto, Japan", description: "Ancient capital with thousands of temples, traditional geisha districts, bamboo forests, and exquisite kaiseki cuisine. Cherry blossoms in spring.", country: "Japan", region: "East Asia", type: "Culture & History", bestSeason: ["Mar-May", "Oct-Nov"], activities: ["Temple Visits", "Tea Ceremony", "Bamboo Forest", "Cherry Blossoms"], budget: "$$", climate: "Temperate" },
  { id: "14", name: "Marrakech, Morocco", description: "Sensory overload in the best way — bustling souks, ornate palaces, rooftop terraces, and the Atlas Mountains as a backdrop.", country: "Morocco", region: "North Africa", type: "Culture & Markets", bestSeason: ["Mar-May", "Sep-Nov"], activities: ["Souks", "Riads", "Desert Trips", "Hammam"], budget: "$", climate: "Arid" },
  { id: "15", name: "Rome, Italy", description: "The Eternal City where ancient ruins meet vibrant street life. Colosseum, Vatican, incredible pasta, and gelato on every corner.", country: "Italy", region: "Europe", type: "History & Food", bestSeason: ["Apr-Jun", "Sep-Oct"], activities: ["Ancient Ruins", "Vatican", "Food Tours", "People Watching"], budget: "$$", climate: "Mediterranean" },
  { id: "16", name: "Petra, Jordan", description: "Ancient Nabataean city carved into rose-red cliffs, one of the New Seven Wonders. Walk through the narrow Siq to reveal the Treasury.", country: "Jordan", region: "Middle East", type: "Archaeological Wonder", bestSeason: ["Mar-May", "Sep-Nov"], activities: ["Hiking", "History", "Photography", "Bedouin Culture"], budget: "$$", climate: "Desert" },
  { id: "17", name: "Cusco & Machu Picchu, Peru", description: "Gateway to the lost Incan citadel high in the Andes. Colonial architecture, vibrant markets, and the legendary Inca Trail.", country: "Peru", region: "South America", type: "History & Trekking", bestSeason: ["May-Sep"], activities: ["Inca Trail", "Ruins", "Markets", "Altitude Acclimatization"], budget: "$$", climate: "Highland" },
  { id: "18", name: "Istanbul, Turkey", description: "Where East meets West — Byzantine churches, Ottoman mosques, the Grand Bazaar, and incredible street food spanning two continents.", country: "Turkey", region: "Europe/Asia", type: "Culture & Food", bestSeason: ["Apr-Jun", "Sep-Nov"], activities: ["Bazaars", "Mosques", "Bosphorus Cruise", "Turkish Bath"], budget: "$", climate: "Mediterranean" },

  // City & Urban
  { id: "19", name: "Tokyo, Japan", description: "Futuristic metropolis where neon-lit streets meet serene shrines. Incredible food scene from Michelin stars to ramen stalls, anime culture, and cutting-edge technology.", country: "Japan", region: "East Asia", type: "City & Food", bestSeason: ["Mar-May", "Sep-Nov"], activities: ["Street Food", "Shopping", "Temples", "Anime Districts"], budget: "$$", climate: "Temperate" },
  { id: "20", name: "New York City, USA", description: "The city that never sleeps — Broadway shows, world-class museums, Central Park, diverse neighborhoods, and iconic skyline views.", country: "USA", region: "North America", type: "City & Entertainment", bestSeason: ["Apr-Jun", "Sep-Nov"], activities: ["Broadway", "Museums", "Central Park", "Food Scene"], budget: "$$$", climate: "Continental" },
  { id: "21", name: "Barcelona, Spain", description: "Gaudí's architectural masterpieces, Mediterranean beaches, tapas bars, and vibrant nightlife. Art, food, and sunshine in perfect balance.", country: "Spain", region: "Europe", type: "City & Beach", bestSeason: ["May-Sep"], activities: ["Architecture", "Beaches", "Tapas", "Nightlife"], budget: "$$", climate: "Mediterranean" },
  { id: "22", name: "Melbourne, Australia", description: "Australia's cultural capital with world-class coffee, street art laneways, diverse food scene, and easy access to the Great Ocean Road.", country: "Australia", region: "Oceania", type: "City & Coffee Culture", bestSeason: ["Nov-Mar"], activities: ["Coffee Culture", "Street Art", "Food Markets", "Great Ocean Road"], budget: "$$", climate: "Temperate" },
  { id: "23", name: "Lisbon, Portugal", description: "Hilly coastal city with pastel-colored buildings, vintage trams, incredible pastéis de nata, and a thriving creative scene.", country: "Portugal", region: "Europe", type: "City & Charm", bestSeason: ["Mar-Oct"], activities: ["Tram Rides", "Fado Music", "Pastries", "Viewpoints"], budget: "$", climate: "Mediterranean" },

  // Wellness & Relaxation
  { id: "24", name: "Ubud, Bali", description: "Spiritual heart of Bali surrounded by rainforest. Yoga retreats, meditation centers, organic cafes, and healing ceremonies.", country: "Indonesia", region: "Southeast Asia", type: "Wellness & Spiritual", bestSeason: ["Apr-Oct"], activities: ["Yoga", "Meditation", "Spa", "Rice Terrace Walks"], budget: "$", climate: "Tropical" },
  { id: "25", name: "Sedona, Arizona", description: "Red rock formations with powerful energy vortexes, world-class spas, stargazing, and spiritual healing in the desert landscape.", country: "USA", region: "North America", type: "Wellness & Nature", bestSeason: ["Mar-May", "Sep-Nov"], activities: ["Vortex Hikes", "Spa", "Stargazing", "Meditation"], budget: "$$", climate: "Desert" },
  { id: "26", name: "Kerala, India", description: "God's Own Country with tranquil backwaters, Ayurvedic treatments, spice plantations, and houseboat cruises through palm-lined canals.", country: "India", region: "South Asia", type: "Wellness & Nature", bestSeason: ["Sep-Mar"], activities: ["Ayurveda", "Houseboat", "Spice Gardens", "Yoga"], budget: "$", climate: "Tropical" },
  { id: "27", name: "Tulum, Mexico", description: "Bohemian beach town with ancient Mayan ruins overlooking turquoise waters, cenote swimming, and trendy wellness retreats.", country: "Mexico", region: "Central America", type: "Beach & Wellness", bestSeason: ["Nov-Apr"], activities: ["Cenotes", "Ruins", "Yoga", "Beach Clubs"], budget: "$$", climate: "Tropical" },

  // Wildlife & Safari
  { id: "28", name: "Serengeti, Tanzania", description: "Witness the Great Migration — millions of wildebeest crossing vast golden plains. Lions, elephants, and giraffes in their natural habitat.", country: "Tanzania", region: "East Africa", type: "Safari & Wildlife", bestSeason: ["Jun-Oct"], activities: ["Game Drives", "Hot Air Balloon", "Migration", "Photography"], budget: "$$$", climate: "Savanna" },
  { id: "29", name: "Galápagos Islands, Ecuador", description: "Living laboratory of evolution where fearless wildlife lets you walk among giant tortoises, blue-footed boobies, and marine iguanas.", country: "Ecuador", region: "South America", type: "Wildlife & Nature", bestSeason: ["Jun-Nov"], activities: ["Snorkeling", "Wildlife", "Hiking", "Kayaking"], budget: "$$$", climate: "Tropical Dry" },
  { id: "30", name: "Borneo, Malaysia", description: "Ancient rainforest home to orangutans, pygmy elephants, and proboscis monkeys. River safaris and canopy walks through pristine jungle.", country: "Malaysia", region: "Southeast Asia", type: "Wildlife & Rainforest", bestSeason: ["Mar-Oct"], activities: ["Orangutan Sanctuaries", "River Safari", "Canopy Walk", "Diving"], budget: "$$", climate: "Tropical" },

  // Winter & Snow
  { id: "31", name: "Lapland, Finland", description: "Winter wonderland with northern lights, reindeer sleigh rides, ice hotels, and the chance to meet Santa Claus in his hometown.", country: "Finland", region: "Europe", type: "Winter Wonderland", bestSeason: ["Dec-Mar"], activities: ["Northern Lights", "Reindeer Rides", "Ice Hotels", "Husky Sledding"], budget: "$$$", climate: "Arctic" },
  { id: "32", name: "Hokkaido, Japan", description: "Japan's winter paradise with powder snow skiing, hot spring onsens, fresh seafood, and the magical Sapporo Snow Festival.", country: "Japan", region: "East Asia", type: "Winter & Food", bestSeason: ["Dec-Mar"], activities: ["Skiing", "Onsen", "Snow Festival", "Seafood"], budget: "$$", climate: "Cold Continental" },
  { id: "33", name: "Banff, Canada", description: "Stunning Rocky Mountain town with turquoise lakes, world-class skiing, wildlife spotting, and cozy mountain lodges.", country: "Canada", region: "North America", type: "Mountain & Adventure", bestSeason: ["Jun-Sep", "Dec-Mar"], activities: ["Skiing", "Lake Louise", "Wildlife", "Hot Springs"], budget: "$$", climate: "Alpine" },

  // Off the Beaten Path
  { id: "34", name: "Bhutan", description: "The last Shangri-La — a Buddhist kingdom measuring Gross National Happiness. Tiger's Nest monastery, pristine forests, and ancient traditions.", country: "Bhutan", region: "South Asia", type: "Spiritual & Remote", bestSeason: ["Mar-May", "Sep-Nov"], activities: ["Monastery Visits", "Trekking", "Festivals", "Archery"], budget: "$$$", climate: "Varies" },
  { id: "35", name: "Faroe Islands", description: "Remote North Atlantic archipelago with dramatic sea cliffs, grass-roofed villages, puffin colonies, and otherworldly landscapes.", country: "Denmark", region: "Europe", type: "Remote & Scenic", bestSeason: ["May-Sep"], activities: ["Hiking", "Bird Watching", "Photography", "Village Exploring"], budget: "$$$", climate: "Maritime" },
  { id: "36", name: "Oman", description: "Hidden gem of the Middle East with dramatic wadis, vast deserts, ancient forts, and genuine Bedouin hospitality without the crowds.", country: "Oman", region: "Middle East", type: "Desert & Culture", bestSeason: ["Oct-Apr"], activities: ["Wadi Swimming", "Desert Camping", "Forts", "Souks"], budget: "$$", climate: "Arid" },

  // Food & Wine
  { id: "37", name: "Tuscany, Italy", description: "Rolling hills dotted with vineyards and medieval hilltop towns. World-class wine, truffle hunting, and cooking classes in rustic farmhouses.", country: "Italy", region: "Europe", type: "Food & Wine", bestSeason: ["Apr-Jun", "Sep-Oct"], activities: ["Wine Tasting", "Cooking Classes", "Truffle Hunting", "Cycling"], budget: "$$$", climate: "Mediterranean" },
  { id: "38", name: "Oaxaca, Mexico", description: "Mexico's culinary capital with mole sauces, mezcal distilleries, vibrant markets, and indigenous Zapotec culture.", country: "Mexico", region: "Central America", type: "Food & Culture", bestSeason: ["Oct-Apr"], activities: ["Food Tours", "Mezcal Tasting", "Markets", "Ruins"], budget: "$", climate: "Temperate" },
  { id: "39", name: "Porto, Portugal", description: "Charming riverside city famous for port wine cellars, azulejo tiles, francesinha sandwiches, and stunning Douro Valley day trips.", country: "Portugal", region: "Europe", type: "Food & Wine", bestSeason: ["May-Sep"], activities: ["Port Wine", "River Cruise", "Food Tours", "Tile Spotting"], budget: "$", climate: "Mediterranean" },
  { id: "40", name: "Bangkok, Thailand", description: "Street food paradise with ornate temples, floating markets, rooftop bars, and the best pad thai you'll ever taste — all incredibly affordable.", country: "Thailand", region: "Southeast Asia", type: "Food & City", bestSeason: ["Nov-Feb"], activities: ["Street Food", "Temples", "Markets", "Rooftop Bars"], budget: "$", climate: "Tropical" },
];
